/**
 * Department Email Routing
 *
 * Sends notification emails to department contacts after interaction records are created.
 * Fire-and-forget: never blocks record insertion, logs all attempts.
 */

import { Resend } from "resend";
import type { IntakeRecord } from "@shared/schema";

// Resend client - instantiated lazily when sending email
let resendClient: Resend | null = null;

function getResendClient(): Resend | null {
  if (!process.env.RESEND_API_KEY) {
    return null;
  }
  if (!resendClient) {
    resendClient = new Resend(process.env.RESEND_API_KEY);
  }
  return resendClient;
}

// Sender email (must be verified in Resend dashboard)
const FROM_EMAIL = process.env.RESEND_FROM_EMAIL || "InBot AI <notifications@xpandai.com>";

export interface DepartmentEmailConfig {
  email: string;
  cc_email: string | null;
}

export interface EmailSendResult {
  success: boolean;
  messageId?: string;
  error?: string;
}

/**
 * Format interaction data into email content
 */
function formatEmailContent(record: IntakeRecord): { subject: string; html: string; text: string } {
  const subject = `[${record.department}] New Intake: ${record.name}`;

  const timestamp = new Date(record.timestamp).toLocaleString("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  });

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: #1a1a1a; border-bottom: 2px solid #3b82f6; padding-bottom: 10px;">
        New Intake Report
      </h2>

      <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
        <tr>
          <td style="padding: 8px 0; color: #666; width: 140px;">Department:</td>
          <td style="padding: 8px 0; font-weight: bold;">${record.department}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #666;">Caller Name:</td>
          <td style="padding: 8px 0;">${record.name}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #666;">Phone:</td>
          <td style="padding: 8px 0;">${record.phone}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #666;">Address:</td>
          <td style="padding: 8px 0;">${record.address || "Not provided"}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #666;">Timestamp:</td>
          <td style="padding: 8px 0;">${timestamp}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #666;">Channel:</td>
          <td style="padding: 8px 0;">${record.channel}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #666;">Language:</td>
          <td style="padding: 8px 0;">${record.language}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #666;">Duration:</td>
          <td style="padding: 8px 0;">${Math.round(record.durationSeconds / 60)} min ${record.durationSeconds % 60} sec</td>
        </tr>
      </table>

      <div style="background: #f8fafc; padding: 15px; border-radius: 8px; margin: 20px 0;">
        <h3 style="margin: 0 0 10px 0; color: #1a1a1a;">Issue Summary</h3>
        <p style="margin: 0; color: #374151;">${record.transcriptSummary || "No summary available"}</p>
      </div>

      <div style="background: #fffbeb; padding: 15px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #f59e0b;">
        <h3 style="margin: 0 0 10px 0; color: #1a1a1a;">Raw Issue Text</h3>
        <p style="margin: 0; color: #374151; font-style: italic;">"${record.intent || "No issue text captured"}"</p>
      </div>

      <p style="color: #9ca3af; font-size: 12px; margin-top: 30px; border-top: 1px solid #e5e7eb; padding-top: 15px;">
        This email was automatically generated by InBot AI. Record ID: ${record.id}
      </p>
    </div>
  `;

  const text = `
New Intake Report
=================

Department: ${record.department}
Caller Name: ${record.name}
Phone: ${record.phone}
Address: ${record.address || "Not provided"}
Timestamp: ${timestamp}
Channel: ${record.channel}
Language: ${record.language}
Duration: ${Math.round(record.durationSeconds / 60)} min ${record.durationSeconds % 60} sec

Issue Summary:
${record.transcriptSummary || "No summary available"}

Raw Issue Text:
"${record.intent || "No issue text captured"}"

---
Record ID: ${record.id}
  `.trim();

  return { subject, html, text };
}

/**
 * Send department notification email
 * Returns result immediately, never throws
 */
export async function sendDepartmentEmail(
  record: IntakeRecord,
  config: DepartmentEmailConfig
): Promise<EmailSendResult> {
  // Get Resend client (lazy initialization)
  const resend = getResendClient();
  if (!resend) {
    console.warn("[email] RESEND_API_KEY not configured, skipping email send");
    return { success: false, error: "RESEND_API_KEY not configured" };
  }

  try {
    const { subject, html, text } = formatEmailContent(record);

    const recipients = [config.email];
    const ccRecipients = config.cc_email ? [config.cc_email] : undefined;

    console.log(`[email] Sending to ${config.email}${config.cc_email ? ` (CC: ${config.cc_email})` : ""}`);

    const { data, error } = await resend.emails.send({
      from: FROM_EMAIL,
      to: recipients,
      cc: ccRecipients,
      subject,
      html,
      text,
    });

    if (error) {
      console.error("[email] Resend error:", error);
      return { success: false, error: error.message };
    }

    console.log(`[email] Sent successfully, message ID: ${data?.id}`);
    return { success: true, messageId: data?.id };
  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : "Unknown error";
    console.error("[email] Exception:", errorMessage);
    return { success: false, error: errorMessage };
  }
}

/**
 * Map unknown departments to known categories
 * Any unrecognized department falls back to "General"
 */
export function normalizeDepartment(department: string): string {
  const knownDepartments = [
    "Public Works",
    "Public Safety",
    "Finance",
    "Parks & Public Property",
    "Parks & Recreation",
    "Sanitation",
    "Utilities",
    "General",
  ];

  // Exact match
  if (knownDepartments.includes(department)) {
    return department;
  }

  // Case-insensitive match
  const normalized = knownDepartments.find(
    (d) => d.toLowerCase() === department.toLowerCase()
  );
  if (normalized) {
    return normalized;
  }

  // Fallback to General
  console.log(`[email] Unknown department "${department}", mapping to "General"`);
  return "General";
}
